"""Add billing and usage columns to user

Revision ID: d10ba76ad91c
Revises: b242a07f9f0c
Create Date: 2026-04-09 02:45:56.719013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10ba76ad91c'
down_revision: Union[str, None] = 'b242a07f9f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_query_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('last_query_reset', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_query_reset')
    op.drop_column('users', 'daily_query_count')
    # ### end Alembic commands ###
