"""Add case folders

Revision ID: b242a07f9f0c
Revises: 4b5c6d7e8f9a
Create Date: 2026-04-08 14:52:20.613810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b242a07f9f0c'
down_revision: Union[str, None] = '4b5c6d7e8f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_folders',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_folders_user_id'), 'case_folders', ['user_id'], unique=False)
    op.create_table('case_folder_documents',
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['case_folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_folder_documents_document_id'), 'case_folder_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_case_folder_documents_folder_id'), 'case_folder_documents', ['folder_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.alter_column('chat_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_chat_sessions_folder_id'), 'chat_sessions', ['folder_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'case_folders', ['folder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_folder_id'), table_name='chat_sessions')
    op.alter_column('chat_sessions', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chat_sessions', 'folder_id')
    op.drop_index(op.f('ix_case_folder_documents_folder_id'), table_name='case_folder_documents')
    op.drop_index(op.f('ix_case_folder_documents_document_id'), table_name='case_folder_documents')
    op.drop_table('case_folder_documents')
    op.drop_index(op.f('ix_case_folders_user_id'), table_name='case_folders')
    op.drop_table('case_folders')
    # ### end Alembic commands ###
