"""add_parent_child_chunking

Revision ID: f2b5f689df2d
Revises: f50c9ed83cff
Create Date: 2026-01-19 23:21:33.142998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b5f689df2d'
down_revision: Union[str, None] = 'f50c9ed83cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add section_title (nullable) - no issue
    op.add_column('document_chunks', sa.Column('section_title', sa.String(length=500), nullable=True))
    
    # Add chunk_type as NULLABLE first
    op.add_column('document_chunks', sa.Column('chunk_type', sa.String(length=20), nullable=True))
    
    # Set default value for existing rows (treat as 'parent' for backward compat)
    op.execute("UPDATE document_chunks SET chunk_type = 'parent' WHERE chunk_type IS NULL")
    
    # Now alter to NOT NULL
    op.alter_column('document_chunks', 'chunk_type', nullable=False)
    
    # Add parent_chunk_id (nullable is fine)
    op.add_column('document_chunks', sa.Column('parent_chunk_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'document_chunks', ['parent_chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'parent_chunk_id')
    op.drop_column('document_chunks', 'chunk_type')
    op.drop_column('document_chunks', 'section_title')
    # ### end Alembic commands ###
